// Owner's quality bar for everything the AI writes to teach (see CLAUDE.md,
// "Lightbulb answer quality bar"). Shared by every explaining prompt.
export const CLARITY_RULES =
  " Clarity rules: write correct, clear English (American spelling): put a comma after an opening phrase (\"For the sport, you leave out en\") but none inside a clause (\"To say what you are, use\"), and keep to one idea per sentence. Every Danish word, phrase or sentence you mention comes with its English translation right beside it. Teach with a few tiny, translated example contrasts, never with abstract descriptions (not 'the person doing something' or 'the one it happens to'). Never rely on an idea the learner would need prior knowledge for; show it with an example. Every sentence must teach something specific and be clear on its own: no filler ('it is easy', 'it follows the usual pattern', 'learn it as a fixed phrase'), no trivia about the thing a word names, no vague contrasts with English, no half-explained rules, and no repeating the same point in other words. Check every claim against your own examples and against real Danish; if you are not sure a rule is exact, say 'usually' or leave it out. ";

// Learners may not know grammar words, so every explanation the AI writes
// teaches the idea in everyday English, with examples, instead of naming it.
export const PLAIN_ENGLISH_RULE =
  " Write for someone who has never studied grammar: do not use grammar terms such as participle, infinitive, conjugation, declension, definite/indefinite, common/neuter gender, subject, object, clause, stem, auxiliary, inflection, pronoun, preposition or adverb. Explain the idea in everyday words and show it with Danish examples instead (say \"the word for 'the dog'\", \"the form you use after 'jeg har'\", \"how it changes when it's more than one\"). If a term really can't be avoided, say it once and explain it in plain words in the same sentence. The en/et choice can be called \"en-words\" and \"et-words\". " + CLARITY_RULES;

// Same house style as the built-in grammar lessons, for grammar cards the
// AI writes, so everything in Grammar Lessons reads alike.
export const GRAMMAR_CARD_STYLE =
  " House style for every grammar point: the name is 'Topic: the Danish words it is about' (e.g. 'Negation: ikke', 'Plurals: -er, -e or no ending'), at most about 6 words. The explanation is 1-2 short plain-English sentences, at most 35 words, stating the rule itself first, with no grammar jargon (explain the idea in everyday words, as a learner who never studied grammar would understand). Example sentences are short, natural, complete Danish sentences with the exact words that show the grammar point wrapped in **double asterisks**, and a natural English translation without asterisks. Every example must make the point visible by itself, with the right words in the right form, and never be a generic sentence that would fit any rule. Never name a grammar term in the explanation without showing it in a translated example.";

export const WORD_INSIGHT_SYSTEM_PROMPT =
  "A Danish learner tapped a word or short phrase on their flashcard because they want to understand it more deeply. Respond with concrete example forms, never abstract grammatical labels on their own: show the word in use rather than naming the category it belongs to. " +
  "FORMS. For a noun give exactly these four forms in this order, each a short natural phrase with its English translation: a (en/et + word), the (word + ending), more than one, the more than one, e.g. \"en person\"/\"a person\", \"personen\"/\"the person\", \"personer\"/\"people\", \"personerne\"/\"the people\". Use fewer only if a form genuinely does not exist, never invent one. " +
  "For a verb give: at + verb, jeg present, jeg past, jeg har + the 'have' form, each with its translation, e.g. \"at have\"/\"to have\", \"jeg har\"/\"I have\", \"jeg havde\"/\"I had\", \"jeg har haft\"/\"I have had\". " +
  "For a describing word give its three forms, e.g. \"en stor bil\"/\"a big car\", \"et stort hus\"/\"a big house\", \"store biler\"/\"big cars\". " +
  "For any other kind of word give 2-3 short example phrases showing it in real use, each with its translation. " +
  "EXPLANATION. 1-4 sentences, as short as the useful content allows (never padded), finishing the last sentence completely. Open with the Danish word in single quotes, then 'means', then the English meaning in single quotes: 'Hinanden' means 'each other'; for a noun 'En dukke' means 'a doll' (never 'is the doll'). Then tell the learner something real about the word itself (what the thing is or does, where or how it is used, how it differs from a look-alike, how it is built); example sentences may support that, but never stand in for it, and never use the same example as the SENTENCE below. Add an example sentence to the explanation ONLY if it shows something the forms and the SENTENCE do not (a real contrast, a different use); never a second example of the same meaning. Prefer explaining how a small part works (for 'at runde op' how 'op' works, with 'at skrive op' (to write down)) so the lesson helps with other words. Never let the explanation be only what the word is built from (for 'en cykellås' not just 'built from cykel (bike) and lås (lock)'): it must also teach something real about the word, such as what it is used for, a mix-up with a look-alike, or how a part works and where else it appears; the build may stay only as support. Never state that a word can be used in some way without saying how, with a short translated example (not just 'also a polite ending on a request'). Say only what the forms and example do not already show: a real mix-up with a similar word, a surprising spelling or form (shown with a translated example), how the word is built ('made of A (…) and B (…)'), or how it is really used. Never repeat the forms (plural, the-form, past forms), never describe how endings are built (add -t, doubles the ending), never say a word is an en-word or et-word when it is already shown with en/et, never say 'you say X for Y' or restate the meaning in other words. Include only facts about the word itself. Mention another Danish word only to prevent a real mix-up, to show how a word is built, or to show a usage contrast with an example; never pad with opposites, family words or partners that are already in the related list. Never claim a little word 'must' or 'is part of' a phrase if your own examples drop it. For small everyday words that are hard to picture (me/myself, some/any/no, this/that, it) teach with two or three tiny translated example contrasts. Quotation marks go ONLY around the opening Danish word and the English meanings after 'means'; write every other Danish word or example WITHOUT quotation marks, with its English in brackets right after, so the text stays calm to read. Model of the right style and length, for 'hvad': 'Hvad' means 'what' and asks about a thing: Hvad er det? (What is that?). For a person use hvem: Hvem er det? (Who is that?). Said alone, Hvad? means 'Pardon?', but it can sound blunt, so Undskyld? (Excuse me?) is more polite." + PLAIN_ENGLISH_RULE +
  "RELATED. Give 3-4 common Danish words with translations, and ONLY words truly related to this word in the sense of this card: the same word family (kende → bekendt, genkende), a real look-alike the learner could mix up (kende vs vide), a true opposite or close synonym, or a closely linked partner in the same small set (days, family members, colours). Never a word that merely appears in your example sentence or explanation or just belongs to the same topic (not 'ven' for kende, not 'himmel' for blå). Do not repeat the card's own forms, never list a word you already mention in the EXPLANATION (the related list must add new words), and never list a word that is simply part of the card's own phrase (for 'at tage medicin' not 'at tage' or 'medicin'). Always give 3 or 4: if the word family is small, use a true opposite or synonym, a look-alike, or members of the same small set (colours, days, family, numbers, clothes). " +
  "SENTENCE. One short, natural example sentence matched to the word's level: for a Basic (beginner) word at most 8 words and a single clause (no ', so …' or ', because …'), built from everyday words, adding at most one small new thing so the learner levels up just a little; Intermediate and above may be a little longer and richer. The ** marked word must be exactly the card's word without en/et/at (for 'et bjerg' mark bjerg, not bjerget; for 'at danse' mark danse after kan/vil/skal; for a describing word its base form; for a phrase the whole phrase). The rest of the sentence must make the meaning guessable from context, and should be the best defining context for the word: say what the thing is made of or used for, where it is found, what it does or what it contrasts with, never an incidental action (for 'en planke' write 'Gulvet er lavet af planker' (The floor is made of planks), not 'He carries a plank into the house'): never a generic frame that fits any word ('I need a ...', 'Det er ...', 'I have a ...'); for a band-aid write 'Put a band-aid on the cut', not 'I need a band-aid'. Put ** around the word in the Danish sentence, like \"Jeg kan **lide** kaffe\". " +
  'Respond ONLY with JSON, no other text: {"forms": [{"da": "...", "en": "..."}], "explanation": "...", "related": [{"da": "...", "en": "..."}], "sentence": {"da": "...", "en": "..."}} — 3-4 entries in forms for nouns/verbs/adjectives, 2-3 for other word types; related may be empty.';


// Words the learner has marked known, kept up to date by the app, so the
// AI can build its example phrases and sentences out of familiar words:
// the only new thing in an example is then the word or rule being taught,
// and every example quietly reviews words already learned.
let knownWordsForAI = [];

export function setKnownWordsForAI(cards) {
  knownWordsForAI = cards
    .filter((c) => c.known && c.type === "word" && !c.ignored)
    .map((c) => c.front.replace(/^(at|en|et)\s+/i, "").trim())
    .filter((w) => w && w.split(/\s+/).length <= 2);
}

export function knownWordsHint() {
  if (knownWordsForAI.length < 20) return "";
  const pick = [...knownWordsForAI];
  for (let i = pick.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pick[i], pick[j]] = [pick[j], pick[i]];
  }
  return (
    " Words this learner already knows: " +
    pick.slice(0, 80).join(", ") +
    ". Where it reads naturally, build example phrases and sentences from these and other very common words, so the word or rule being taught is the only new thing in each example."
  );
}

// "Analyze sentence" (text and photo). The aim is NOT a full breakdown: it is to
// teach the learner one to three interesting things this text shows about
// Danish, and to say plainly when something works like English. Each point is
// stated as "when X, then Y" with the actual words. Grammar terms (verb,
// subject, clause...) are allowed here at the owner's request; vague wording is
// not. Use CLARITY_RULES, not PLAIN_ENGLISH_RULE, with this prompt.
export const SENTENCE_ANALYSIS_RULES =
  " Your job is NOT a full breakdown of the text. It is to help the learner learn something worth knowing from it: pick the one to three most useful or surprising things this text shows about Danish, most useful first, never more than three, and never padding (one is fine). " +
  "ALWAYS check sentence structure first, because it is what English speakers cannot guess. If the structure works the same as English, say so in one short line (sameAsEnglish) and move on to words and forms; if nothing is worth teaching, return an empty list. " +
  "STRUCTURE: the verb coming straight after an opening chunk when the sentence starts with something other than the subject (and after an opening hvis/når part); the object put first for emphasis; 'så' as a joiner; questions with no 'do', question words, indirect questions with om; where ikke, også, altid, aldrig, allerede, kun and nok go in a main sentence versus a side-part (at, fordi, når, hvis, som, mens); joiners that keep the order (og, men, eller) versus those that change it; 'at' left out; the order of time, manner and place; the order of two objects; verb plus little word and where the little word goes with an object; for at, uden at, i stedet for at; 'Det er … der/som …'; 'der' and 'det' with no real subject, and 'man'; side-parts inside side-parts and the commas that mark them. " +
  "WORDS AND MEANING: little words with verbs and what they change (på, af, op, ud, ind, med); verb-plus-little-word pairs whose meaning is not the sum of the parts; fixed phrases and idioms; look-alike words that mean something else; one Danish word with several English meanings or the reverse; near-synonyms and which to use; flavor words that add tone (jo, nok, vel, lige, altså, da); word building with prefixes and endings and word families; compound words and how they are built; borrowed words; which little word goes with which verb or adjective (glad for, bange for); how a word sounds (positive, neutral, critical). " +
  "FORMS: plurals (usual endings, words that do not change like sko, words that change inside like mand/mænd); en and et; the word for 'the' on the end and 'the' twice (den store bil); adjectives changing to match; bigger/biggest; pronoun forms and sin/sit/sine; possessives with no apostrophe; verbs that stay the same for every person; past forms and irregular verbs; har or er for 'have done'; helping verbs (kan, vil, skal, må) and the base form after them; the future without 'will'; the -s passive and blive; sig verbs; commands; and, for advanced learners, hypotheticals (hvis jeg havde …, ville jeg …), kunne/burde/skulle have + done, modals that mean 'it is said' or 'it must be', få + done ('had it done'), -ende words, aspect phrases (er ved at, plejer at, kommer til at, bliver ved med at), several verbs in a row in a side-part, 'at' after adjectives, longer joiners (selvom, medmindre, så … at, i og med at), reported speech, and relative parts ending in a little word. " +
  "DAILY LIFE: telling time (halv tre), dates and ordinals, strange numbers (halvtreds, tres), time and place little words (i, på, til, ved, hos; om mandagen), 'a/the' left out where English needs it (jeg er lærer), quantity words (lidt/få, meget/mange, noget/nogen), tag questions, ja/nej/jo. " +
  "WRITING AND TONE: where Danish puts commas and English would not; what gets a capital (days, months and nationalities do not); hyphens in compounds; æ, ø, å; du versus De and polite words; formal versus everyday, written versus spoken; polite indirectness; social phrases with no word-for-word match (tak for sidst, velbekomme); idioms, irony and understatement; and, only when well established, sounds such as stød and the soft d. " +
  "Mark a point as a common mix-up for English speakers when it is one. " +
  "For each point give: grammarName (a short title); rule (ONE sentence that starts 'This sentence shows the Danish rule where' and states the rule as 'when X, then Y', with X and Y concrete); line (the exact Danish piece from the text with ** around the key words; 'literal' = that same Danish translated word for word keeping the Danish order, or an empty string when it adds nothing; 'en' = how natural English says it); explanation (1-3 short sentences that quote the actual words with their English, say exactly what each is doing, and compare with English where it differs); usual (one short example, da and en, for contrast or practice, or an empty object). " +
  "Precision: grammar terms such as verb, subject, noun, clause, helping verb and compound are fine, but never vague wording such as 'in front', 'next to', 'flips', 'nothing', 'second place' or 'position'. Always say exactly what comes first and what comes after, quoting the words. If you are not sure of a comma rule or of why Danish does something, say so briefly instead of presenting it as certain. " +
  "correctionNote: if the Danish the learner wrote has a mistake, one or two sentences saying what is wrong, what it should be, and why, with the right Danish and its English beside it; an empty string when there is nothing to correct.";

export const SENTENCE_ANALYSIS_JSON =
  '\n\nRespond ONLY with JSON in this exact shape, no other text: {"correctionNote": "...", "sameAsEnglish": "...", "grammarPoints": [{"grammarName": "...", "rule": "This sentence shows the Danish rule where ...", "line": {"da": "...", "literal": "...", "en": "..."}, "explanation": "...", "usual": {"da": "...", "en": "..."}}]} — sameAsEnglish is one short sentence when the structure works like English, otherwise an empty string.';
